language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wipescarcity/docker-cast -f Dockerfile.dev .

script:
  - docker run -e CI=true wipescarcity/docker-cast npm run test

