language: generic
sudo: required
services:
  - docker
before_install:
 - docker build -t wipescarcity/docker-cast -f Dockerfile
script:
 - docker run -e CI=true wipescarcity/docker-cast npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  region: 'us-east-1'
  app: 'docker'
  env: 'docker-react'
  bucket_name: 'elasticbeanstalk-us-east-1-506868433032' # it’s a place to store file by s3.
  bucket_path: 'docker-react' # the name of folder
    on:
      branch: master

